version: "3.1"

services:
  project:
    build:
      dockerfile: Dockerfile
    command: 'bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - my_db

  my_db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./postgres_base:/var/lib/postgresql

  celery:
    build:
      dockerfile: Dockerfile
    command: 'celery -A my_project worker -l info -B'
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq

  memcached:
    image: memcached
    entrypoint:
      - memcached
      - -m 64
    ports:
      - "11211:11211"