# Generated by Django 4.1.3 on 2022-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('list_currency', models.TextField()),
            ],
        ),
    ]
