# Generated by Django 4.1.3 on 2023-01-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exchangerates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='list_currency',
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='currency_name_1',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='currency_name_2',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='rate_buy',
            field=models.DecimalField(decimal_places=4, default=True, max_digits=7),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='rate_sell',
            field=models.DecimalField(decimal_places=4, default=True, max_digits=7),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
