# Generated by Django 4.1.3 on 2023-01-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_exchangerates_list_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='date',
        ),
    ]
